### ISSUE TITLE
Getting Started / Example project does not work with conan 2.0.6

### ISSUE THREAD

**Issue by apivovarov** [conan-io/examples#116] opened 2023-06-15 20:36 UTC
[getting_started](https://docs.conan.io/1/getting_started.html)

Example project 
```
$ git clone https://github.com/conan-io/examples.git && cd examples/libraries/poco/md5
```

First error - Missing dependencies error when running
```
conan install ..

# it should be replaced with 
conan install .. --build=missing
```

Second Error
```
conanfile.txt: Writing generators to /Users/pivovaa/workspace/conan-examples/libraries/poco/md5
ERROR: Invalid generator 'cmake'. Available types: CMakeToolchain, CMakeDeps, MesonToolchain, MSBuildDeps, MSBuildToolchain, NMakeToolchain, NMakeDeps, VCVars, QbsProfile, VirtualRunEnv, VirtualBuildEnv, AutotoolsDeps, AutotoolsToolchain, PkgConfigDeps, BazelDeps, BazelToolchain, IntelCC, XcodeDeps, XcodeToolchain, PremakeDeps
```
```
$ cat conanfile.txt
[requires]
poco/1.9.4

[generators]
cmake
```

Third error
```
conan install poco/1.9.4@
ERROR: Conanfile not found at /Users/pivovaa/workspace/conan-examples/libraries/poco/md5/poco/1.9.4@
```

Very strange. How new people are going to try conan if even Getting Started is broken???

**Comment by RubenRBS** [comment] 2023-06-15 20:41
Hi! I'm closing this as duplicate of https://github.com/conan-io/docs/issues/3258, 1 issue in the whole organization is usually enough 😄

**Closed by RubenRBS** 2023-06-15 20:41 UTC
